default_platform(:android)

platform :android do
  desc "Push app metadata to Google Play"
  lane :push_metadata do
    supply(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_screenshots: true
    )
  end
end
