name: bigblueblocks
description: A simple puzzle game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#010816"
  image: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
