# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Pull metadata from App Store Connect"
  lane :pull_metadata do
    deliver(
      run_validator: false,
      skip_binary_upload: true,
      skip_screenshots: false,
      skip_metadata: false,
      force: true
    )
  end

  desc "Push ONLY the app icon to App Store Connect"
  lane :push_icon_only do
    # Copy our generated icon to the location deliver expects
    sh "cp Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png fastlane/metadata/app_icon.png"
    
    deliver(
      skip_binary_upload: true,
      skip_screenshots: true,
      skip_metadata: true,
      force: true
    )
  end

  desc "Build and install directly to the connected device (1 Year Expiry)"
  lane :install_direct do
    # 1. Build the IPA in Ad-Hoc Release mode
    build_app(
      scheme: "Runner",
      export_method: "ad-hoc",
      silent: true
    )

    # 2. Install the IPA onto the connected device
    # Note: Requires 'brew install ios-deploy'
    install_on_device(
      ipa: Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]
    )
  end
end
